Team-Plants/PLANTS

- .husky/pre-commit
- package-lock.json
- package.json
**husky**를 세팅하였습니다
husky만 설치하면 stage된 파일 이외에도 모든 파일들을 검사해서 시간이 오래 걸리는 문제 등으로 인해 **lint-staged**도 같이 세팅했어요
preinstall을 설정해놔서 해당 pr이 merge가 되면
`npm i`
만 해주시면 husky가 적용됩니당
commit이 허용되면 제가 작성한 문구도 보실 수 있어요 😚 (이모티콘 찾는 데에 시간 더 걸린 거는 비밀입니다)
commit을 하기 전에 stage상태에 있는 .ts와 .tsx파일을 검사하고 prettier에서 문제가 발생해 commit을 못하는 모습을 볼 수 있어요!
깃 크라켄에서도 이렇게 에러가 뜨더라구요 ㅎㅎ
> [#2] husky, lint-staged 설정

- src/assets/fonts/fonts.css
- src/styles/globals.css
- src/styles/variables.css
- tsconfig.json
- 봐야하는 부분
button도 기본설정 했습니다.
- 궁금한 점
더 추가할 부분이 있다면 알려주세요.
> [#5] global style 설정

- src/constants/common.ts
- src/libs/api.ts
- baseURL 주소 맞는지 
- 디렉토리 구조에 맞게 파일을 작성했는지
없음
> [#3] axios 설정하기 

- package-lock.json
- package.json
- src/components/formProvider/FormProvider.tsx
- src/constants/auth.ts
- src/types/FormValue.ts
devtools를 부착한 FormProvider 컴포넌트를 만들었습니다.
거의 슬희님의 코드를 참고해서 작성했어요,, 
에러메시지와 이메일, 비밀번호, 닉네임의 정규표현식을 상수로 만들었습니다.
> [#7] react-hook-form 세팅

- package-lock.json
- package.json
- src/components/formProvider/SignFormProvider.tsx
- src/types/SignFormValue.ts
Devtool을 dev dependencies로 이동시켰고 컴포넌트와 타입의 네이밍을  변경하였습니다.
x
> [#20] react-hook-form 세팅 수정

- .github/DISCUSSION_TEMPLATE/General.yml
- .github/DISCUSSION_TEMPLATE/Q&A.yml
yml 방식이 어색해서 맞게 썼나 모르겠어요 
https://docs.github.com/ko/discussions/managing-discussions-for-your-community/syntax-for-discussion-category-forms
위 링크 참고하면서 만들었어요
추가적으로 테스트해볼 곳이 있나요??
> [#19] github discussion yml 파일 추가

- src/components/card/card.module.css
- src/components/card/card.tsx
- src/styles/breakpoints.css
- web 이미지 o
- web 이미지 x
- tablet 이미지 o
- tablet 이미지 x
- mobile  이미지 o
- mobile 이미지 x
> [#43] card 컴포넌트

- src/components/button/add/add.module.css
- src/components/button/arrow/arrow.module.css
- src/components/button/arrow/arrowButton.tsx
- src/components/button/arrow/inActiveButton.tsx
- src/components/button/auth/auth.module.css
- src/components/button/button.module.css
- src/components/button/buttonGroup.tsx
- src/components/button/column/column.module.css
- src/components/button/dashBoard/create/createDashBoard.module.css
- src/components/button/dashBoard/dashBoard.module.css
- src/components/button/dashBoard/dashBoardButton.tsx
- src/components/button/dashBoard/delete/deleteDashBoard.module.css
- src/components/card/card.module.css
- src/components/chip/category/category.module.css
- src/components/chip/circle/circle.module.css
- src/components/chip/number/number.module.css
- src/components/chip/number/numberChip.tsx
- src/components/chip/plus/plus.module.css
- src/components/chip/plus/plusChip.tsx
- src/components/chip/progress/progress.module.css
- src/components/chip/progress/progressChip.tsx
- src/components/layout/authLayout.module.css
- src/components/layout/authLayout.tsx
- src/pages/index.module.css
- src/styles/globals.css
wrapper에서 container로 수정하였습니다
font-weight variables.css로 적용 안 된 것들 적용했습니당
> [#48] style className 수정

- src/components/button/add/add.module.css
- src/components/button/add/addButton.tsx
- src/components/button/auth/auth.module.css
- src/components/button/button.module.css
- src/components/button/button.tsx
- src/components/button/buttonGroup.tsx
- src/components/button/column/column.module.css
- src/components/button/column/columnButton.tsx
- src/components/button/dashBoard/create/createDashBoard.module.css
- src/components/button/dashBoard/create/createDashBoardButton.tsx
- src/components/button/dashBoard/dashBoard.module.css
- src/components/button/dashBoard/dashBoardButton.tsx
- src/components/button/dashBoard/delete/deleteDashBoard.module.css
- src/components/button/dashBoard/delete/deleteDashBoardButton.tsx
- src/components/button/dashBoard/return/returnButton.module.css
- src/components/table/invitation/invitationItem.tsx
- src/components/table/invitation/invitationList.tsx
- src/components/table/invitedDashboard/invitedItem.tsx
- src/components/table/member/memberItem.tsx
- src/pages/[id]/mydashboard.tsx
- src/remotes/device.d.ts
버튼을 눌렀을 때 실행할 함수를 prop으로 받게 하였습니다
media query로 적용하였습니다! (주석처리 해 놓으신 분들이 많더라구요 죄송해요 🥲🥺)
> [#74] button 컴포넌트 수정

- src/components/Input/Input.module.css
- src/components/Input/Input.tsx
- src/components/Input/emailInput.tsx
- src/components/Input/nickName.tsx
- src/components/Input/passwordCheck.tsx
- src/components/Input/passwordInput.tsx
- src/components/header/dashboardHeader/dashboardHeader.module.css
- src/components/header/dashboardHeader/dashboardHeader.tsx
- src/components/profile/profileImg.module.css
- src/components/profile/profileImg.tsx
- src/components/table/password/passwordTable.module.css
- src/components/table/password/passwordTable.tsx
- src/components/table/profile/profileTable.module.css
- src/components/table/profile/profileTable.tsx
- src/constants/auth.ts
- src/hooks/useAuthInput.ts
- src/pages/mypage/index.tsx
- src/pages/mypage/mypage.module.css
- src/styles/globals.css
- src/types/SignFormValue.ts
mypage ui 개발했어요
mypage input이 기존 input이랑 크기가 달라서 default는 그대로 두고 `바꿀 경우에만 size를 props`로 받게 했어요
`components/profile/profileTable` 에 프로필 이미지 변경 로직에 해당하는 컴포넌트를 따로 빼놨어요
공통으로 backgound-color가 (--gray-10) 이길래 글로벌로 적용했어요 ! 참고해주세요 😃
> [#47] mypage ui 개발

- package-lock.json
- package.json
- src/components/header/dashboardHeader/UsersImage.tsx
- src/components/header/dashboardHeader/dashboardHeader.module.css
- src/components/header/dashboardHeader/dashboardHeader.tsx
- src/components/header/dashboardHeader/usersImage.module.css
- src/components/nameBadge/nameBadge.module.css
- src/components/nameBadge/nameBadge.tsx
- src/components/table/password/passwordTable.tsx
- src/components/table/profile/profileTable.tsx
- src/styles/variables.css
header 초대된 유저들 뱃지 겹침 구현헸어요
데스크탑
테블릿
모바일
> [#76] style : header 345

- src/pages/[id]/mydashboard.tsx
- 제출 시 email이 안 넘어가는 문제 발생
- useMutation으로 수정
> [#97] 초대하기 수정

- next.config.js
- src/api/card.ts
- src/api/column.ts
- src/api/member.ts
- src/components/button/add/addButton.tsx
- src/components/modal/addTodoModal/addTodoModal.tsx
- src/components/modal/button/modalButtonSet.tsx
- src/components/modal/button/modalDefaultButton.module.css
- src/components/modal/button/modalDefaultButton.tsx
- src/components/modal/input/defaultInput/defaultInput.tsx
- src/components/modal/input/imgInput/imgInput.tsx
- src/components/modal/input/selectInput/managerOption.tsx
- src/components/modal/input/selectInput/selectInput.module.css
- src/components/modal/input/selectInput/selectInput.tsx
- src/components/modal/textarea/textarea.tsx
- src/libs/api.ts
- src/pages/api/getToken.ts
- src/pages/boards/index.tsx
- src/types/column.ts
- src/utils/utility.ts
- 이미지를 보내고 싶은데 어떤 string으로 보내야하는지 모르겠어요(해결)
```
const handleChange = (e) => {
const targetFile = e.target.files[0];
setValue(imageUrl, targetFile);   //api로 보낼 값
}
...
<input type='file' onchange={handleChange}/>
```
formData를 만들고 value 값을 추가했고, withAuthhandler를 거치지 않고 header에 token을 달고 바로 보냈어요! with 수빈님🌱
> [#100] 할일 생성 모달 기능 구현

- .eslintrc.json
- package-lock.json
- package.json
- src/api/card.ts
- src/api/comment.ts
- src/components/button/card/kebab.module.css
- src/components/button/card/kebabButton.tsx
- src/components/card/card.tsx
- src/components/chip/number/numberChip.tsx
- src/components/modal/button/modalButtonSet.tsx
- src/components/modal/button/modalDefaultButton.tsx
- src/components/modal/editTodoModal/editTodoModal.tsx
- src/components/modal/modalLayout.tsx
- src/components/modal/todoModal/comment.tsx
- src/components/modal/todoModal/todoModal.module.css
- src/components/modal/todoModal/todoModal.tsx
- src/constants/queryKeys.ts
- src/pages/[id]/mydashboard.tsx
- src/pages/boards/index.tsx
- src/remotes/custom.d.ts
- src/types/Card.ts
- src/types/Comment.ts
- src/types/User.ts
- tsconfig.json
지금 **새로고침 해야만 post, put, delete** 되는데 이 문제를 해결해야 해요
해당 문제 도움 주실 수 있는 분 계신가요 ㅠㅠ🥺
카드 수정하기 기능에서 상태랑 담당자는 default 값으로 못 갖고오고 있어요, 근데 다른 작업 상황도 지금 상태는 따로 data로 받아오지 않고 문자열로 넣는 것 같은데 맞나요 ???
할 일 카드 수정하기에서 태그 부분이 글 쓰고 enter하면 이상하게 완성되고 있어서 이 부분 고쳐야 될 것 같아요
할 일 카드 put은 좀 수정할게요 ..
> [#63] 할 일 카드 모달 api

- src/components/modal/addTodoModal/addTodoModal.tsx
addtomodal postcard api 연결했어요
x
> [#135] addtomodal 데이터 카드 api 연결

- src/components/modal/newDashboardModal/newDashboardModal.tsx
- src/components/sideMenu/SideMenu.tsx
- src/components/table/editDashboard/editDashboard.tsx
- src/pages/mydashboard/index.tsx
> [#134] 사이드메뉴 렌더링 문제 해결

- src/components/modal/addTodoModal/addTodoModal.tsx
> [#144] addTodoModal form enterkey submit 막음

- src/components/button/dashBoard/create/paginationCreateDashboard/paginationCreateDashboard.module.css
- src/components/layout/layout.module.css
- src/components/table/editDashboard/editDashboard.module.css
- src/components/table/invitation/invitationList.module.css
- src/components/table/invitedDashboard/invitedList.module.css
- src/components/table/member/memberList.module.css
- src/pages/dashboard/[id]/edit/dashboardEditPage.module.css
- src/pages/dashboard/[id]/index.tsx
- src/pages/mypage/mypage.module.css
> [#143] layout을 사용하는 페이지들의 가로 길이 반응형 디자인 수정

- src/components/modal/input/tagInput/tagInput.tsx
- src/pages/dashboard/[id]/edit/index.tsx
- src/pages/dashboard/[id]/index.tsx
태그 input에 한글로 작성시 두번 실행되서 수정했어요
alert가 에러떠서 콘솔로 바꿨어요
> [#140] 태그 input 수정

- src/api/card.ts
- src/components/button/card/kebabButton.tsx
- src/constants/queryKeys.ts
- src/pages/dashboard/[id]/index.tsx
카드 삭제하면 새로고침 해야만 적용되길래 적용했어요
120번 모달 머지되면 삭제 시 모달 사라지게 적용해야 합니다.
> [#118] 할 일 카드 delete

- src/components/column/column.tsx
- src/components/modal/todoModal/comment.tsx
- src/components/modal/todoModal/todoModal.module.css
- src/components/modal/todoModal/todoModal.tsx
- src/pages/dashboard/[id]/index.tsx
> [#119] 댓글 기능 수정

- src/components/header/dashboardHeader/dashboardHeader.module.css
- src/components/header/dashboardHeader/dashboardHeader.tsx
- src/pages/api/logout.ts
- src/pages/mypage/index.tsx
- src/pages/mypage/mypage.module.css
- 마이페이지 로그아웃 버튼 추가 및 로그아웃 기능
- 헤더 프로필 클릭 시 마이페이지 이동 추가
> [#151] feat: 로그아웃 추가 및 헤더 마이페이지 이동 추가

- src/pages/index.tsx
> [#158] fix: 로그아웃 시 랜딩페이지 접근 처리

- src/components/card/card.tsx
- src/components/chip/category/categoryChip.tsx
- src/components/column/column.tsx
- src/components/modal/input/tagInput/tagInput.tsx
-카드 컴포넌트 태그 기본값으로 들어있는 부분 데이터로 수정
> [#155] fix: 카드 태그 기본값 수정

- src/components/header/dashboardHeader/dashboardHeader.module.css
- src/components/layout/layout.module.css
- src/components/layout/layout.tsx
- src/components/sideMenu/sideMenu.module.css
https://github.com/Team-Plants/PLANTS/assets/127609484/7db84fc7-6e1a-4d82-897f-d106a3f84b03
https://github.com/Team-Plants/PLANTS/assets/127609484/d9146c6d-4cb6-441b-9c26-8702f398369e
> [#154] layout에 포함된 사이드메뉴, 헤더 위치 고정

- src/components/button/auth/auth.module.css
- src/components/button/auth/authButton.tsx
- src/components/layout/authLayout.module.css
> [#172]로그인 페이지 스타일 수정

- src/api/column.ts
- src/pages/dashboard/[id]/index.tsx
컬럼 수정, 삭제 시 즉각적으로 화면이 리렌더링이 될 수 있도록 리액트 쿼리 Mutation 코드를 추가하였습니다.
> [#173] 컬럼 수정, 삭제 즉시 반영

- src/components/modal/input/imgInput/imgInput.module.css
- src/components/modal/input/imgInput/profileImgInput.tsx
- src/components/table/profile/profileTable.tsx
기존 프로필 이미지를 볼 수 있어요
변경하기 버튼을 눌러서 프로필 이미지를 변경할 수 있어용
> [#165] 계정관리 프로필 이미지

- src/components/button/card/kebabButton.tsx
- src/components/chip/progress/progressChip.tsx
- src/components/modal/todoModal/todoModal.module.css
- src/components/modal/todoModal/todoModal.tsx
- src/pages/dashboard/[id]/index.tsx
> [#164] todomodal card data 연결

- src/components/card/card.tsx
- src/components/modal/input/tagInput/tagInput.tsx
- src/utils/utility.ts
> [#180] 컬러 배지 함수 수정

- src/components/button/dashBoard/dashBoard.module.css
- src/components/modal/modalLayout.module.css
- src/components/sideMenu/SideMenu.tsx
- src/components/sideMenu/sideMenu.module.css
- src/pages/index.module.css
- src/pages/index.tsx
- 대시보드 버튼 크기를 고정적인 값 지정
- 플로팅 액션 버튼 크기 조절
- 랜딩페이지 소개글 축약
> [#183] 부분적인 CSS 수정

- src/components/layout/layout.tsx
- src/components/sideMenu/SideMenu.tsx
- src/pages/mydashboard/index.tsx
-[x] mydashboard 페이지에서 대시보드 생성 시 사이드메뉴에 대시보드 추가되지 않는 문제 해결
https://github.com/Team-Plants/PLANTS/assets/127609484/27d9fccd-644a-45f2-b1ab-b6350aa00718
> [#175] mydashboard 페이지에서 대시보드 생성 시 사이드메뉴에 대시보드 추가되지 않는 문제 해결

- src/components/table/invitation/invitationList.tsx
- src/pages/dashboard/[id]/edit/index.tsx
> [#191] 배포 환경에서 관리 버튼으로 대시보드 수정 페이지 접근 시 초대하기 모달이 팝업되고 닫히지 않는 문제 해결 3차 시도

- src/components/modal/modalLayout.tsx
> [#193] 배포 환경에서 관리 버튼으로 대시보드 수정 페이지 접근 시 초대하기 모달이 팝업되고 닫히지 않는 문제 해결 4차 시도

- src/components/button/auth/auth.module.css
https://github.com/Team-Plants/PLANTS/assets/127609484/f834a184-e219-4fe8-9297-9fb9d91b4a7d
https://github.com/Team-Plants/PLANTS/assets/127609484/1b05b908-0b2f-4c6f-9a2b-f48ab051c34b
> [#201] 로그인, 회원가입 페이지에서 입력 조건을 충족했을 때 로그인, 회원가입 버튼의 디자인 오류 수정

- src/components/modal/modalLayout.tsx
- src/pages/dashboard/[id]/index.tsx
- 컬럼 관리 모달 외부 클릭 시 안닫히는 오류 수정했어요
https://github.com/Team-Plants/PLANTS/assets/138510303/d3964222-96b5-4d41-bed3-cd99ccd67ff3
https://github.com/Team-Plants/PLANTS/assets/138510303/03aa8f6b-51c7-4438-a653-82b2a46461bb
> [#203] fix : 컬럼 관리 모달 외부 클릭 시 닫힘 수정
